### ISSUE TITLE
Import from HP to HPX [EmptyNameError|305]: Title.name is not allowed to be empty:

### ISSUE THREAD

**Issue by Micro-kernel** [happypandax/happypandax#193]
**Describe the issue**
I tried to import my HP database to HPX 0.12.4, but got an EmptyNameError.  I don't know by which gallery caused this, and the db file works well in the old HP.  The logs also don't give any information. I tried importing the db with an old version of HPX(0.9.2) I had lying around and the import works there without problems. So it must be something introduced with the newer versions of HPX. 

**To Reproduce**
1. Go HP to HPX in the GUI
2. Select the old db and start conversion
3. ArrowParseWarning: the .get() parsing method woth a format string will parse more strictly in versiuon 0.15.0. See https://github.com/crsmithdev/arrow/issues/612 for more details
4. Progress to 75%
5. [EmptyNameError|305]: Title.name is not allowed to be empty:

**Expected behavior**
The import to finish correctly.

**Logs**
No logs were written during the import sadly. But I uploaded my HP db to be able to reproduce the error. Password is **HPX** and link will expire in 7 days:
https://send.firefox.com/download/34d934e75703fdef/#3C8B7ztwLFSpvf4iKTNLYg

**Environment:**
 - OS: [Win 10]
 - HPX Version [0.12.4]

**Additional context**

Import works with  [0.9.2], but now with [0.12.4]

**Comment by twiddli** [comment]
Hi, for now you can use v0.9.2 to import and then apply the v0.12.4 update and it'll automatically update.

**Comment by twiddli** [comment]
should be fixed in `v0.13.0`

**Comment by Micro-kernel** [comment]
Hey, thanks for the update. I just tried the import again with 0.13.3 and am still getting the same error ([EmptyNameError|305]: Title.name is not allowed to be empty:)
