### ISSUE TITLE
[Docker] Failed to configure built-in ESearch server 0.13.1 error

### ISSUE THREAD

**Issue by waz1500** [happypandax/happypandax#210]
**Describe the issue**
The Docker Image is still broken in 0.13.1 .
Windows build is working fine and shows login page. 
Similar to issue https://github.com/happypandax/happypandax/issues/209

**To Reproduce**
1. Download latest docker image
2. Start it with fresh settings (remove any previous config folders)
3. See error

**Logs**
```
HPX_DATA was defined, data will now be at: /data
Running HPX version 0.13.1

Using sqlite database
'Failed to configure built-in ESearch server, process exit code: 1 also see /data/logs/esearch_stdout.log '

'Could not establish connection to ESearch server, aborting. '
Sentry is attempting to send 0 pending error messages

Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Environment:**
 - OS: Docker Image
 - Version 84.0.4147.135 (Official Build) (64-bit)
 - HPX Version 0.13.1

**Comment by GlassedSilver** [comment]
Same issue here.

OS is Docker container based on official Dockerhub image, supplied as custom unRAID OS template.

**Comment by nopenopenop** [comment]
I have the same issue on Windows too after the upgrade. The error in the esearch_stdout.log is:

`X\bin\win32\elasticsearch\jdk"" was unexpected at this time.`

**Comment by reluce** [comment]
Same problem here with WSL and Docker:

```
$ cat data/logs/esearch_stdout.log
[ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [happypandax-testarossa_naoka_ram] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.9.0.jar:7.9.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.9.0.jar:7.9.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.9.0.jar:7.9.0]
Caused by: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:111) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.9.0.jar:7.9.0]
        ... 6 more
uncaught exception in thread [main]
java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:111)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
```

When I specify a non root user in docker-compose.yml with `user: <uid>`, I get following message instead when executing `docker-compose up`:
```happypandax_1  | HPX_DATA was defined, data will now be at: /data
happypandax_1  | Running HPX version 0.13.1
happypandax_1  | [Errno 13] Permission denied: '__version__'
happypandax_1  | Traceback (most recent call last):
happypandax_1  |   File "run.py", line 15, in <module>
happypandax_1  |   File "happypanda/main.py", line 318, in start
happypandax_1  |   File "happypanda/migrate.py", line 74, in apply_migrations
happypandax_1  |   File "happypanda/migrate.py", line 58, in save_migration_version
happypandax_1  | PermissionError: [Errno 13] Permission denied: '__version__'
happypandax_1  | Sentry is attempting to send 0 pending error messages
happypandax_1  | Waiting up to 2 seconds
happypandax_1  | Press Ctrl-C to quit```

**Comment by Poosaurus** [comment]
As for nopenopenop's issue on windows I believe this link should be of some help https://stackoverflow.com/questions/51131300/elastic-search-startup-error-common-was-unexpected-at-this-time
I tried the second solution, setting JAVA_HOME, and then I also changed the port elasticsearch was running on because it was already in use in my case. Hope this helps.

**Comment by Poosaurus** [comment]
As for nopenopenop's issue on windows I believe this link should be of some help https://stackoverflow.com/questions/51131300/elastic-search-startup-error-common-was-unexpected-at-this-time
I tried the second solution, setting JAVA_HOME, and then I also changed the port elasticsearch was running on because it was already in use in my case. Hope this helps.

**Comment by twiddli** [comment]
should be fixed in `v0.13.2`

**Comment by lukemin** [comment]
> should be fixed in `v0.13.2`

still not work

date | stream | content
-- | -- | --
2020-08-29 04:38:34 | stdout | Press Ctrl-C to quit
2020-08-29 04:38:34 | stdout | Waiting up to 2 seconds
2020-08-29 04:38:34 | stdout | Sentry is attempting to send 0 pending error messages
2020-08-29 04:38:34 | stdout | 'Could not establish connection to ESearch server, aborting. '
2020-08-29 04:38:19 | stdout | 'Failed to configure built-in ESearch server, process exit code: still running; also see /data/logs/esearch_stdout.log '
2020-08-29 04:36:11 | stdout | Starting up, please wait...
2020-08-29 04:35:51 | stdout | Using sqlite database
2020-08-29 04:35:50 | stdout | Running HPX version 0.13.2
2020-08-29 04:35:50 | stdout | HPX_DATA was defined, data will now be at: /data

**Comment by twiddli** [comment]
Please follow #215

**Comment by austinfttwxd** [comment]
is this still under development? Im having the same issue running it through docker on my unraid server and organizing my library of doujinshi is about half the reason I built it in the first place.
