### ISSUE TITLE
Exception when adding galleries

### ISSUE THREAD

**Issue by Dystasia** [happypandax/happypandax#212]
**Describe the issue**
When adding new galleries through the single or scan function, I get the Failed to add new gallery! error. Logs down bellow. The gallery does actually get added but it is not found in the inbox/library immediately. The gallery only shows up, only after a restart of the server or attempting to finding it after quite some time.

**To Reproduce**
Using the default settings of a fresh install, scan a directory using "Scan" or add a new gallery using the "+ New" after submitting you'll get the error related to an AddItem.added command shown in the error logs. 

**Expected behavior**
No errors or exceptions related to the AddItem command.

**Logs**

_Activity:_
Aug-08 16:02:32--INFO   [command].happypanda.core.commands.database_cmd: Adding 5 items 
Aug-08 16:02:34--INFO   [command].happypanda.core.commands.database_cmd: Finished item adding with no errors, added 5 items, failed 0 
Aug-08 16:02:34--ERROR  [command].happypanda.core.services: Command AddItem(126) raised an exception 
Traceback (most recent call last):
  File "happypanda\core\services.py", line 451, in _callback_wrapper
  File "src\\gevent\\greenlet.py", line 769, in gevent._gevent_cgreenlet.Greenlet.get
  File "src\\gevent\\greenlet.py", line 364, in gevent._gevent_cgreenlet.Greenlet._raise_exception
  File "gevent\_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "src\\gevent\\greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "happypanda\core\db.py", line 4190, in wrapper
  File "happypanda\core\command.py", line 104, in _run
  File "happypanda\core\command.py", line 356, in _main_wrap
  File "happypanda\core\commands\database_cmd.py", line 1317, in main
  File "happypanda\core\command.py", line 761, in emit
  File "happypanda\core\command.py", line 701, in invoke_on_plugins
  File "happypanda\core\command.py", line 734, in _check_types
AssertionError: Wrong types were used for command 'AddItem.added'. Types used (<class 'tuple'>), types expected (<class 'tuple'>, <class 'dict'>)

_Error:_
Aug-08 16:02:34--ERROR  [command].happypanda.core.services: Command AddItem(126) raised an exception 
Traceback (most recent call last):
  File "happypanda\core\services.py", line 451, in _callback_wrapper
  File "src\\gevent\\greenlet.py", line 769, in gevent._gevent_cgreenlet.Greenlet.get
  File "src\\gevent\\greenlet.py", line 364, in gevent._gevent_cgreenlet.Greenlet._raise_exception
  File "gevent\_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "src\\gevent\\greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "happypanda\core\db.py", line 4190, in wrapper
  File "happypanda\core\command.py", line 104, in _run
  File "happypanda\core\command.py", line 356, in _main_wrap
  File "happypanda\core\commands\database_cmd.py", line 1317, in main
  File "happypanda\core\command.py", line 761, in emit
  File "happypanda\core\command.py", line 701, in invoke_on_plugins
  File "happypanda\core\command.py", line 734, in _check_types
AssertionError: Wrong types were used for command 'AddItem.added'. Types used (<class 'tuple'>), types expected (<class 'tuple'>, <class 'dict'>)

**Environment:**
 - Windows 10
 - Firefox and Chrome

**Additional context**
Fresh Install of version 0.13.1

**Comment by twiddli** [comment]
should be fixed in `v0.13.2`

**Comment by Dystasia** [comment]
Error is still happening in 0.13.2 using both scan and single 
![image](https://user-images.githubusercontent.com/2527787/91642792-38ab4400-e9fc-11ea-8be5-f870db77c0a2.png)

**Comment by twiddli** [comment]
fixed in `v0.13.3`
